{% set name = "json-logging" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json-logging-{{ version }}.tar.gz
  sha256: 60a02a1daa168a08aa0a41eeeda63e92500ab08170491bdd326cf00d17f656f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - json_logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bobbui/json-logging-python
  summary: JSON Python Logging
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
