{% set name = "json-logging" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/json-logging-{{ version }}.tar.gz
  sha256: 7c938750996a1cc66042b516caf75214513bcc25a105012865496864f5f3983b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - json_logging
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bobbui/json-logging-python
  summary: JSON Python Logging
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
